### ISSUE TITLE
Sample server returns internal server error after granting scope

### ISSUE THREAD

**Issue by sandeep-at-airlift** [paypal/paypal-retail-node#5]
I'm able to successfully login and grant scope to my app (I am functioning as the merchant and the app developer), however the call to the redirect URL fails with `Internal Server Error`

    2017-01-23T17:41:53.334824+00:00 app[web.1]: SyntaxError: Unexpected token s
    2017-01-23T17:41:53.334833+00:00 app[web.1]:     at Object.parse (native)
    2017-01-23T17:41:53.334834+00:00 app[web.1]:     at Object.module.exports.completeAuthentication (/app/index.js:160:26)
    2017-01-23T17:41:53.334835+00:00 app[web.1]:     at /app/server.js:69:12
    2017-01-23T17:41:53.334839+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    2017-01-23T17:41:53.334840+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:131:13)
    2017-01-23T17:41:53.334841+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    2017-01-23T17:41:53.334841+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    2017-01-23T17:41:53.334842+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:277:22
    2017-01-23T17:41:53.334843+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
    2017-01-23T17:41:53.334844+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:271:10)

The url for the call back (with redacted code is) 

    https://airlift-paypal-auth.herokuapp.com/returnFromPayPal?code=C101.XXXXXX&scope=https%3A%2F%2Furi.paypal.com%2Fservices%2Fpaypalhere%20https%3A%2F%2Fapi.paypal.com%2Fv1%2Fpayments%2F.*%20https%3A%2F%2Fapi.paypal.com%2Fv1%2Fpayments%2Fsale%2F.*%2Frefund%20openid%20https%3A%2F%2Fapi.paypal.com%2Fv1%2Fpayments%2Frefund&state=something

This is in the **sandbox environment**.

Any ideas on what the issue is? I was assuming this would be a simple thing to get up and running.

**Comment by Premierapp** [comment]
Did you figure out why ?
